parameters:
#    parameter_name: value

services:
  app.crawler.wikipedia:
    class: AppBundle\Service\WikipediaCrawlerService
  app.dataResearcher.wikipedia:
    class: AppBundle\Service\WikipediaDateResearcherService